version: '3.8'

services:
  mlflow:
    build: .
    ports:
      - "5050:5000"
    volumes:
      - ./artifacts:/mlflow/artifacts
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
